[Feat/#19] app bar 기능 구현
OMZigak/ANDROID pull request #21
Opened 2024-07-05 16:44 UTC by hyoeunjoo

## ✅ 𝗖𝗵𝗲𝗰𝗸-𝗟𝗶𝘀𝘁
- merge할 브랜치의 위치를 확인해 주세요(main❌/develop⭕)
- 리뷰가 필요한 경우 리뷰어를 지정해 주세요
- 리뷰는 (아직 미정)에 진행됩니다.
- P1 단계의 리뷰는 (아직 미정)까지 반영합니다.
- Approve된 PR은 assigner가 머지하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.

## 📌 𝗜𝘀𝘀𝘂𝗲𝘀
- closed #19 

## 📎𝗪𝗼𝗿𝗸 𝗗𝗲𝘀𝗰𝗿𝗶𝗽𝘁𝗶𝗼𝗻
- [ ] jetpack navi를 이용해서 공통 app bar 구현

## 📷 𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁

https://github.com/OMZigak/ANDROID/assets/137873124/418bc0b4-935e-4827-b8c0-8986b356e0bf

## 💬 𝗧𝗼 𝗥𝗲𝘃𝗶𝗲𝘄𝗲𝗿𝘀
와프 보니까 home 화면에는 app bar가 안 보이더라구요
뒤에 내 모임이랑 마이페이지에만 보이게 하면 되는 점 참고해서 봐주세요!

맞게 한 건지 잘 모르겠습니다.. 냉철한 코리 부탁드리겠습니다....

2024-07-05 17:05 UTC, yskim6772 approved these changes
최고최고 !! 수고하셨슴당 🌻

2024-07-05 17:05 UTC, yskim6772 commented on feature/src/main/res/layout/activity_main.xml
> +                    app:layout_constraintStart_toStartOf="@id/toolbar_image"
start 위치 수정해서 textview가 화면의 가로 기준 중앙에 위치하게 하면 좋을 것 같아요 !! : )

2024-07-05 17:05 UTC, yskim6772 commented on feature/src/main/java/com/teamkkumul/feature/MainActivity.kt
> +        }
굿 !! 아주 좋아용 👍🏻

2024-07-05 17:21 UTC, chanubc requested changes
너어어무 고생많으셨습니다!

일단 뒤로가기 버튼이 커스텀 되지 않는 것 같아서..
```kotlin
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <data>

        <variable
            name="title"
            type="String" />
    </data>

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/white">

        <com.google.android.material.appbar.AppBarLayout
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:background="@null"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent">

            <androidx.appcompat.widget.Toolbar
                android:layout_width="match_parent"
                android:layout_height="50dp"
                android:minHeight="0dp">

                <TextView
                    android:id="@+id/tv_appbar_cancel"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginStart="22dp"
                    android:clickable="true"
                    android:paddingHorizontal="6dp"
                    android:paddingVertical="10dp"
                    android:text="@string/appbar_cancel"
                    android:textAppearance="@style/TextAppearance.DontBe.body_regular_14"
                    android:textColor="@color/gray_11" />

                <TextView
                    android:id="@+id/tv_appbar_title"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center"
                    android:text="@{title}"
                    android:textAppearance="@style/TextAppearance.DontBe.body_semi_16"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent"
                    tools:text="테스트" />
            </androidx.appcompat.widget.Toolbar>

            <View
                android:layout_width="match_parent"
                android:layout_height="1dp"
                android:background="@color/gray_2" />

        </com.google.android.material.appbar.AppBarLayout>

    </androidx.constraintlayout.widget.ConstraintLayout>
</layout>
```
이런식으로 공통 앱바 레이아웃 따로 만들어서 사용해야 할것 같습니다ㅠㅠ
여기서 appBarLayout 태그는 제거 하셔도 되요!

``` kotlin
   <include
            android:id="@+id/appbar_posting"
            layout="@layout/view_appbar"
            app:title="@{@string/posting_appbar_title}" />
```
fragment혹은 activity에서는 이렇게 title에 값을 넣어서 사용하면 됩니다!

좌측 기본 뒤로가기 버튼이 커스텀 되지 않음 -> 이 문제가 해결 되지 않을 것 같아서
저렇게 layout만들어서 사용해야 할 것 같아요!

2024-07-05 17:21 UTC, chanubc commented on feature/src/main/res/layout/activity_main.xml
> +            android:layout_height="wrap_content"
p1 : toolbar 전체 높이는 50dp에요!

2024-07-05 17:21 UTC, chanubc commented on feature/src/main/res/layout/activity_main.xml
> +                android:layout_height="wrap_content">
p2 : toolbar의 경우 toolbar내부가 복잡하지 않으면 이러한 constraint를 중첩해서 쓸 필요는 없답니다!

2024-07-05 17:21 UTC, chanubc commented on feature/src/main/res/layout/activity_main.xml
> +                     />
p2 : 한번 둘른 constraint를 지우고
가운데 정렬이 되어야 하는 TextView만
```kotlin
   android:layout_gravity="center"
```
속성을 넣어도 충분 할 것 같습니다!

2024-07-05 17:21 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/MainActivity.kt
> +        setToolBar(navController)
```kotlin
  val appBarConfiguration = AppBarConfiguration(navController.graph)
  binding.toolbar.setupWithNavController(navController, appBarConfiguration)
```
p1 : 제 본의 도는 appBarConfiguration을 활용해서 nav_graph 에 걸려있는 프레그먼트 들의 앱바를 통일하는게 목적이였어요!
이 코드 넣어보면 어떤 느낌인지 감이 올겁니다!
직접 테스트 해봤는데 두가지 문제점이 있네요..
1. 좌측 기본 뒤로가기 버튼이 커스텀 되지 않음
2. compose Fragment에서는 이상하게 app bar가 적용이 되지 않음.

좌측 기본 뒤로가기 버튼만 커스텀 되면 사용 하기 좋다 생각합니다!
한번 이 코드 넣어서 테스트 해보시고 말씀해주세요

2024-07-07 18:29 UTC, chanubc requested changes
공통 구분선 확인해 주세요!

2024-07-07 18:29 UTC, chanubc commented on feature/src/main/res/layout/fragment_my_group.xml
> +
p1 : 요거 삭제해 주세요! 공통 컴포넌트에 구분선을 넣어 주세요. 그리고 match parent 사용보다 constarint제약을 걸고 0dp를 설정하는 것이 더 낫습니다.

2024-07-07 18:29 UTC, chanubc commented on feature/src/main/res/layout/view_toolbar.xml
> +            android:id="@+id/toolbar"
p1 : view_toolbar로 네이밍 바꿔주세요!

2024-07-07 18:29 UTC, chanubc commented on feature/src/main/res/layout/view_toolbar.xml
> +            android:id="@+id/toolbar"
시스템 자체의 네이밍을 쓰는 것은 좋지 않습니다!

2024-07-07 18:29 UTC, chanubc commented on feature/src/main/res/navigation/nav_graph.xml
> +        android:label="내 모임"
p1 : 요것도 string값 추출한 것으로 사용해주세요!

2024-07-07 18:29 UTC, chanubc commented on feature/src/main/res/navigation/nav_graph.xml
> +        android:label="마이페이지"
p1 : 요것도 마찬가지~

2024-07-07 18:29 UTC, chanubc commented on feature/src/main/res/values/strings.xml
> +    <string name="home_title">홈 화면</string>
p1 : 필요없는 요쇼는 삭제 해주세요

2024-07-07 18:29 UTC, chanubc commented on feature/src/main/res/values/strings.xml
> +    <!--    홈화면-->
p2 :  바텀네비게이션 이 더 좋을듯?

2024-07-07 18:33 UTC, hyoeunjoo commented on feature/src/main/res/layout/view_toolbar.xml
> +            android:id="@+id/toolbar"
넵!!

2024-07-07 18:45 UTC, chanubc approved these changes
쵝오!!! 머지하세용

2024-07-07 18:46 UTC, merged